#!/bin/sh

##  File:    qms-config
##
##  Purpose: Provide a file to save personal qmail-scanner configuration
##           options. This file should be edited for your server and
##           saved somewhere so that it survives qmail-scanner and
##           qms-analog upgrades.
##

#  Was the "install" option given?
if [ "$1" != "install" ]; then
  INSTALL=
else
  INSTALL="--install"
fi

##  Definition of Options
##
##  domain             - your primary email domain, where your postmaster
##                       account is located
##  admin              - your postmaster username, normally "postmaster"
##  local-domains      - list all of your local email domains for this qmail
##                       server, separated by commas
##  add-dscr-hdrs      - enable descriptive email headers
##  dscr-hdrs-text     - "Header" for the header
##  ignore-eol-check   - ignore end of line characters in email headers
##  sa-quarantine      - enable/disable quarantining email identified as spam
##  sa-delete          - enable/disable deleting email identified as spam; 
##                       if 0, deletion is disabled; if positive, the value 
##                       over "required_hits" to start deletion
##  sa-reject          - enable/disable rejection of emails identified as spam
##  sa-subject         - spam-identifying test to be prepended to the subject
##                       header
##  sa-alt             - use alternative "fast" Spamassassin processing
##                       provided in the "st" patch
##  sa-debug           - turn on default qmail-scanner debugging; very verbose 
##                       and annoying
##  notify             - comma-separated list parties to notify when a virus 
##                       is quarantined; see the qmail-scanner docs for more 
##                       details
##  redundant          - enable/disable allowing the scanners to scan any zip 
##                       files and the original "raw" email file
##  qms-monitor        - [yes|no] enable qms-monitor Account Monitoring
##  qms-monitor-accts  - list of email accounts to be monitored, separated by 
##                       commas
##                       Example: "acct1@dom2.com,acct2@dom1.com"
##  qms-monitor-dests  - list of destination paths for monitored email messages
##                       Note 1: locations here will be saved underneath
##                               .../qmailscan/qms-monitor; a cron job can later
##                               copy from that location to an alternate email 
##                               domain used for account monitoring.
##                       Note 2: each entry in this array corresponds to the 
##                               email address in the same location of the 
##                               qms-monitor-accts list above - i.e., 
##                               qms-monitor-accts[2] msgs get stored at
##                               qms-monitor-dests[2] - thus, ORDER DOES MATTER
##                       Note 3: DO NOT include a leading "/" on these paths - 
##                               they will typically be entries that ultimately 
##                               belong in /home/vpopmail/domains - so start with
##                               the domain name.
##                       Example: "mon.dom2.com/acct1/Maildir/new,mon.dom1.com/acct2/Maildir/new"
##

./configure \
--qs-user vpopmail \
--qs-group vchkpw \
--qmaildir "/var/qmail" \
--spooldir "/var/qmail/qmailscan" \
--bindir "/var/qmail/bin" \
--admin postmaster \
--domain host.domain.ru \
--admin-fromname "Spamorez_Administrator" \
--local-domains "host.domain.ru" \
--scanners fast_spamassassin,clamdscan \
--skip-text-msgs yes \
--notify admin,recips \
--redundant yes \
--block-password-protected no \
--ignore-eol-check yes \
--add-dscr-hdrs yes \
--dscr-hdrs-text "X-Spamorez" \
--sa-subject "***SPAM***" \
--sa-quarantine 1 \
--sa-delete 2 \
--sa-reject yes \
--sa-alt yes \
--sa-debug yes \
--sa-report yes \
--log-crypto yes \
--skip-setuid-test \
--settings-per-domain yes \
--sa-socket "/var/spool/spamd/spamd" \
"$INSTALL"
