#!/bin/sh

echo "Allow make mirror"
sysctl kern.geom.debugflags=16

cp /etc/fstab /etc/fstab.orig

dev0=`cat /etc/fstab.orig | awk  '$2 == "/"  {print $1}'  | awk '{i=split($0, Name, "/"); print Name[3]}' |  awk '{i=split($0, Name, "s1"); print Name[1]}'`

echo $dev0

echo "make mirror"
gmirror label -v -b round-robin gm0 /dev/$dev0

echo "Start gmirror on boot"
echo geom_mirror_load="YES" >> /boot/loader.conf

echo "modify fstab"
sed "s/\/dev\/$dev0/\/dev\/mirror\/gm0/" < /etc/fstab.orig  > /etc/fstab

echo "
********************************
********************************
Done!
Not forget add another mirrors!
# gmirror insert gm0 /dev/ad6
********************************
********************************"
