#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles/qmail
WORK_DIR=/usr/src/qmail
CONF_DIR=/home/SRC/qmail/CONF/qmail-1.03
PATCH_DIR=/home/SRC/qmail/PATCH/qmail-1.03

####################################################
##echo "В FreeBSD 6.1 нужно прописать линки"
ln -s /usr/local/lib/libssl.so.5 /usr/local/lib/libssl.so.4
ln -s /usr/local/lib/libcrypto.so.5 /usr/local/lib/libcrypto.so.4
####################################################
echo "1. Создаем необходимые директории...."
echo
sleep 2

mkdir -p $WORK_DIR
mkdir -p /data/qmail/package
mkdir -p /var/log/qmail
ln -s /var/log/qmail /data/qmail/log
ln -s /data/qmail /var/qmail
ln -s /data/qmail/package /package
#ln -s /home /usr/home
echo "Done!"
echo
sleep 2

#####################################################
echo "2. Добавляем необходимых пользователей и группы"
echo "ВНИМАНИЕ!!!! Прежде чем добавлять проверить свободные uid и gid!!!!!!!"
echo "Должны быть в промежутке между 200 и 300, не более 500!!!!"
echo
sleep 10
pw groupadd nofiles -g 300
pw useradd alias -g nofiles -d /var/qmail/alias -s /sbin/nologin -u 300
pw useradd qmaild -g nofiles -d /var/qmail -s /sbin/nologin -u 301
pw useradd qmaill -g nofiles -d /var/qmail -s /sbin/nologin -u 302
pw useradd qmailp -g nofiles -d /var/qmail -s /sbin/nologin -u 303
pw groupadd qmail -g 301
pw useradd qmailq -g qmail -d /var/qmail -s /sbin/nologin -u 304
pw useradd qmailr -g qmail -d /var/qmail -s /sbin/nologin -u 305
pw useradd qmails -g qmail -d /var/qmail -s /sbin/nologin -u 306
echo "Add vpopmail users and groups"
pw groupadd vchkpw -g 302
pw useradd vpopmail -g vchkpw -m -d /home/vpopmail -s /sbin/nologin -u 307
echo "Done!"
echo
sleep 2


########################################################
echo "3. Распаковываем qmail, ucspi-tcp и daemontools..."
echo
sleep 2
cd  $WORK_DIR
tar zxvf $SRC_DIR/qmail-1.03.tar.gz
tar zxvf $SRC_DIR/ucspi-tcp-0.88.tar.gz
chmod 1755 /package
cd /package
tar zxvf $SRC_DIR/daemontools-0.76.tar.gz
echo "Done!"
echo
sleep 2

########################################################
echo "4. Next, we setup special logging directories..."
echo
sleep 2
cd /var/log/qmail
mkdir qmail-send qmail-smtpd qmail-pop3d
chown -R qmaill:wheel /var/log/qmail
chmod -R 750 /var/log/qmail
echo "Done!"
echo
sleep 2
########################################################
echo "5. And set up the supervise script directories..."
echo
sleep 2
mkdir /var/qmail/supervise
cd /var/qmail/supervise
mkdir -p qmail-smtpd/log qmail-send/log qmail-pop3d/log
chmod +t qmail-smtpd qmail-send qmail-pop3d
echo "Done!"
echo
sleep 2
########################################################
echo "6.Setting conf-split and conf-spawn"
echo
sleep 2
echo 211 > $WORK_DIR/conf-split
echo 255 > $WORK_DIR/conf-spawn
echo "Done!"
echo
sleep 2

########################################################
echo "6.Установка spamcontrol"

# ftp http://www.fehcom.de/qmail/spamcontrol/spamcontrol-2418_tgz
#mkdir -p $WORK_DIR
cd $WORK_DIR/qmail-1.03

cp $SRC_DIR/spamcontrol-2418.tgz $WORK_DIR/qmail-1.03
tar xvf spamcontrol-2418.tgz

#echo /var/qmail > $WORK_DIR/conf-qmail
# ln -s $WORK_DIR/find-systype find-systype.sh
#make

#cp $CONF_DIR/qmail-bad* $WORK_DIR

$WORK_DIR/qmail-1.03/install_spamcontrol.sh

cd $pwd

########################################################
echo "7. Применяем необходимые qmail patch... (OutCom)"
echo
sleep 2
cd $WORK_DIR/qmail-1.03
echo "Applying standard qmail patch..."
patch < $PATCH_DIR/qmail-103.patch
sleep 2
#echo "Applying qmailqueue patch..."
#patch < $PATCH_DIR/qmailqueue.patch
#sleep 2

#echo "Applying SMTP authentication patch..."
#cp $PATCH_DIR/base64.c ./
#cp $PATCH_DIR/base64.h ./
#patch < $PATCH_DIR/auth-jms1.4a.patch
#sleep 2
#echo "Applying patch for backup in-out smtp trafik"
#patch < $PATCH_DIR/qmail-log.patch
#sleep 2
#echo "Applyng patch badrcptto"
#patch < $PATCH_DIR/badrcptto_Makefile.patch
#sleep 2
#patch < $PATCH_DIR/badrcptto_qmail-smtpd.patch
#sleep 2
echo "Applyng patch qmail-send-mime"
patch < $PATCH_DIR/qmail-send.mime.patch
sleep 2
echo "Applyng patch qmail-date-localtime"
patch < $PATCH_DIR/qmail-date-localtime.patch
sleep 2
echo "*********************************************************  Applyng patch qmail-1.03-bind-interface.pa"
patch < $PATCH_DIR/qmail-1.03-bind-interface.patch
sleep 2
echo "Done!"
echo
sleep 2
###########################################################
echo "8. Устанавливаем Qmail..."
echo
sleep 2
echo "Архивируем патченые исходники"
echo
sleep 2
cd $WORK_DIR
tar cvfz $SRC_DIR/qmail-1.03-src.tar.gz qmail-1.03
sleep 2
echo "Компилируем Qmail"
sleep 2
cd $WORK_DIR/qmail-1.03
gmake man && gmake setup check
echo "Done!"
echo
sleep 2
###########################################################
echo "9. Устанавливаем ucspi-tcp..."
echo
sleep 2
cd $WORK_DIR/ucspi-tcp-0.88/
make
make setup check
echo "Done!"
echo
sleep 2
############################################################
echo "10. Устанавливаем daemontools..."
echo
sleep 2
cd /package/admin/daemontools-0.76
package/install
echo "Done!"
echo
sleep 2
###########################################################
echo "11. Настраеваем Qmail..."
echo
sleep 2
echo "SaveMail..."
mkdir /var/qmail/backup_mail
chown alias:qmail /var/qmail/backup_mail
echo '|/var/qmail/bin/savemail' > /var/qmail/alias/.qmail-log
cp $CONF_DIR/savemail /var/qmail/bin/
touch /var/qmail/control/badrcptto
touch /var/qmail/control/badmailfrom
touch /data/qmail/control/smtproutes
cp $CONF_DIR/qmail-badhelo /data/qmail/control/badhelo

echo 8000000 > /var/qmail/control/databytes
echo "Устанавливаем Qmail алиасы....."
sleep 2
echo root > /var/qmail/alias/.qmail-root
ln -s /var/qmail/alias/.qmail-root /var/qmail/alias/.qmail-postmaster
ln -s /var/qmail/alias/.qmail-root /var/qmail/alias/.qmail-mailer-daemon
ln -s /var/qmail/alias/.qmail-root /var/qmail/alias/.qmail-anonymous
echo
echo "Local host, domain, rcpthosts...."
$WORK_DIR/config-fast $HOSTNAME
echo "Done!"
echo
sleep 2
############################################################
echo "12. Отключение Sendmail..."
echo
sleep 2
killall -9 sendmail
mv /usr/sbin/sendmail /usr/sbin/sendmail.old
chmod 000 /usr/sbin/sendmail.old
echo "" >> /etc/rc.conf
echo "#### Disable Sendmail" >> /etc/rc.conf
echo "sendmail_enable=\"NO\"" >> /etc/rc.conf
echo "sendmail_submit_enable=\"NO\"" >> /etc/rc.conf
echo "sendmail_outbound_enable=\"NO\"" >> /etc/rc.conf
echo "sendmail_msp_queue_enable=\"NO\"" >> /etc/rc.conf
ln -s /var/qmail/bin/sendmail /usr/lib/sendmail
ln -s /var/qmail/bin/sendmail /usr/sbin/sendmail
echo "Done!"
echo
sleep 2
#############################################################
echo "13.Устанавливаем Vpopmail"
cd $WORK_DIR
tar zxvf $SRC_DIR/vpopmail-5.4.13.tar.gz
cd vpopmail-5.4.13
./configure --prefix=/home/vpopmail --enable-ip-alias-domains --enable-logging=p
make && make install-strip
ln -s /home/vpopmail/domains /data/qmail
##############################################################
echo "14.Настраиваем супервизор"
echo "Copying supervise scripts to their correct locations..."
echo
sleep 2
cp $CONF_DIR/pop3d_run /var/qmail/supervise/qmail-pop3d/run
cp $CONF_DIR/pop3d_log /var/qmail/supervise/qmail-pop3d/log/run
cp $CONF_DIR/smtpd_run /var/qmail/supervise/qmail-smtpd/run
cp $CONF_DIR/smtpd_log /var/qmail/supervise/qmail-smtpd/log/run
cp $CONF_DIR/send_run /var/qmail/supervise/qmail-send/run
cp $CONF_DIR/send_log /var/qmail/supervise/qmail-send/log/run
cp $CONF_DIR/rc /usr/local/etc/rc.d/200-qmail.sh

echo Done!
echo "Copying rc and qmailctl scripts to proper locations..."
echo
sleep 2
cp $CONF_DIR/rc /var/qmail/qmail
cp $CONF_DIR/qmailctl /var/qmail/bin/
echo Done!
echo
sleep 2
echo "Setting needed permisions..."
echo
sleep 2
chmod 755 /var/qmail/rc /var/qmail/bin/qmailctl
chmod 751 /var/qmail/supervise/qmail-pop3d/run
chmod 751 /var/qmail/supervise/qmail-pop3d/log/run
chmod 751 /var/qmail/supervise/qmail-smtpd/run
chmod 751 /var/qmail/supervise/qmail-smtpd/log/run
chmod 751 /var/qmail/supervise/qmail-send/run
chmod 751 /var/qmail/supervise/qmail-send/log/run
echo ./Maildir > /var/qmail/control/defaultdelivery
echo 255 > /var/qmail/control/concurrencyremote
chmod 644 /var/qmail/control/concurrencyremote
echo 30 > /var/qmail/control/concurrencyincoming
chmod 644 /var/qmail/control/concurrencyincoming
ln -s /data/qmail/bin/qmailctl /usr/bin

ln -s /var/qmail/supervise/qmail-send /service/qmail-send
ln -s /var/qmail/supervise/qmail-pop3d /service/qmail-pop3d 
ln -s /var/qmail/supervise/qmail-smtpd /service/qmail-smtpd

echo "Done!"
echo
echo "Setup Relaying"
sleep 2
echo '127.:allow,RELAYCLIENT=""' >> /etc/tcp.smtp
qmailctl cdb
echo "Done!"
echo
sleep 2


echo "Qmail полностью установлен!!!!"

#echo "Starting qmail ....."
#qmailctl start

cd $pwd