#!/bin/sh

# For Red Hat chkconfig
# chkconfig: - 80 30
# description: the qmail MTA

PATH=/var/qmail/bin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin
export PATH

QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`

SERVICE=/service

case "$1" in
start)
echo "Starting qmail..."
echo ""
if svok $SERVICE/qmail-send ; then
svc -u $SERVICE/qmail-send $SERVICE/qmail-send/log
echo "Starting qmail-send"
else
echo "qmail-send supervise not running"
fi
if svok $SERVICE/qmail-smtpd ; then
svc -u $SERVICE/qmail-smtpd /service/qmail-smtpd/log
echo "Starting qmail-smtpd"
else
echo "qmail-smtpd supervise not running"
fi
if svok $SERVICE/qmail-pop3d ; then
svc -u $SERVICE/qmail-pop3d $SERVICE/qmail-pop3d/log
echo "Starting qmail-pop3d"
else
echo "qmail-pop3d supervise not running"
fi
if [ -d /var/lock/subsys ]; then
touch /var/lock/subsys/qmail
fi
;;
stop)
echo "Stopping qmail..."
echo ""
echo " qmail-smtpd"
svc -d $SERVICE/qmail-smtpd $SERVICE/qmail-smtpd/log
echo " qmail-send"
svc -d $SERVICE/qmail-send $SERVICE/qmail-send/log
echo " qmail-pop3d"
svc -d $SERVICE/qmail-pop3d $SERVICE/qmail-pop3d/log
if [ -f /var/lock/subsys/qmail ]; then
rm /var/lock/subsys/qmail
fi
;;
stat)
svstat $SERVICE/qmail-send
svstat $SERVICE/qmail-send/log
svstat $SERVICE/qmail-smtpd
svstat $SERVICE/qmail-smtpd/log
svstat $SERVICE/qmail-pop3d
svstat $SERVICE/qmail-pop3d/log
qmail-qstat
;;
doqueue|alrm|flush)
echo "Flushing timeout table and sending ALRM signal to qmail-send."
/var/qmail/bin/qmail-tcpok
svc -a $SERVICE/qmail-send
;;
queue)
qmail-qstat
qmail-qread
;;
reload|hup)
echo "Sending HUP signal to qmail-send."
svc -h $SERVICE/qmail-send
;;
pause)
echo "Pausing qmail-send"
svc -p $SERVICE/qmail-send
echo "Pausing qmail-smtpd"
svc -p $SERVICE/qmail-smtpd
echo "Pausing qmail-pop3d"
svc -p $SERVICE/qmail-pop3d
;;
cont)
echo "Continuing qmail-send"
svc -c $SERVICE/qmail-send
echo "Continuing qmail-smtpd"
svc -c $SERVICE/qmail-smtpd
echo "Continuing qmail-pop3d"
svc -c $SERVICE/qmail-pop3d
;;
restart)
echo "Restarting qmail:"
echo "* Stopping qmail-smtpd."
svc -d $SERVICE/qmail-smtpd /service/qmail-smtpd/log
echo "* Sending qmail-send SIGTERM and restarting."
svc -t $SERVICE/qmail-send /service/qmail-send/log
echo "* Sending qmail-pop3d SIGTERM and restarting."
svc -t $SERVICE/qmail-pop3d /service/qmail-pop3d/log
echo "* Restarting qmail-smtpd."
svc -u $SERVICE/qmail-smtpd /service/qmail-smtpd/log
;;
cdb)
tcprules /etc/tcp.smtp.cdb /etc/tcp.smtp.tmp < /etc/tcp.smtp
chmod 644 /etc/tcp.smtp.cdb
echo "Reloaded /etc/tcp.smtp."
;;
help)
cat <<HELP
stop -- stops mail service (smtp connections refused, nothing goes out)
start -- starts mail service (smtp connection accepted, mail can go out)
pause -- temporarily stops mail service (connections accepted, nothing leaves)
cont -- continues paused mail service
stat -- displays status of mail service
cdb -- rebuild the tcpserver cdb file for smtp
restart -- stops and restarts smtp, sends qmail-send a TERM & restarts it
doqueue -- schedules queued messages for immediate delivery
reload -- sends qmail-send HUP, rereading locals and virtualdomains
queue -- shows status of queue
alrm -- same as doqueue
flush -- same as doqueue
hup -- same as reload
HELP
;;
*)
echo "Usage: $0 {start|stop|restart|doqueue|flush|reload|stat|pause|cont|cdb|queue|help}"
exit 1
;;
esac

exit 0

