#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles
WORK_DIR=/usr/src/pbx
CONF_DIR=/home/SRC/pbx/CONF
PATCH_DIR=/home/SRC/pbx/PATCH

mkdir -p $WORK_DIR

#echo "Asterisk"
#cd $WORK_DIR

#echo "Configure DB PEARS"

#tar zxvf $SRC_DIR/DB-1.7.14RC1.tgz -P -C /usr/local/lib/php
#cp -R /usr/local/lib/php/DB-1.7.14RC1/* /usr/local/lib/php
#rm -R /usr/local/lib/php/DB-1.7.14RC1

cd /usr/ports/sysutils/pidof

make all && make install && make clean

cd $pwd