#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles
WORK_DIR=/usr/src
CONF_DIR=/home/SRC/web/CONF
PATCH_DIR=/home/SRC/web/PATCH

/usr/local/etc/rc.d/apache22 start

####################################################
echo "Распаковываем ssh"

PORT_PATH=/usr/ports/www/apache22
cd $PORT_PATH

cp $PATCH_DIR/* $PORT_PATH/files

make BATCH=yes FORCE_PKG_REGISTER=1 FORCE_PKG_INSTALL=yes  \
install

if [ `grep apache22_enable=\"YES\" /etc/rc.conf | wc -l` -eq 0 ]
then

# .........
echo '
### Apache2
apache22_enable="YES"
' >> /etc/rc.conf

fi

/usr/local/etc/rc.d/apache22 start

# make clean

cd $pwd