#!/bin/bash
#
# Удаление старых файлов в карантинах спамореза
#

_deloldfiles="/data/qmail/bin/tools/deloldfiles"
################# backup_mail #############################
# Кол-во дней хранения файлов
_backup_mail_DAY="150"
_backup_mail_DEL="/data/qmail/backup_mail"
$_deloldfiles $_backup_mail_DEL $_backup_mail_DAY

################# Карантин спамореза ###########################
# Кол-во дней хранения файлов
_qmail_scanner_DAY="100"
_qmail_scanner_DEL="/data/qmail/qmailscan/quarantine/new"
$_deloldfiles $_qmail_scanner_DEL $_qmail_scanner_DAY

################# Карантин KAV #####################################
# Кол-во дней хранения файлов
#_kav_DAY="100"
#_kav_DEL="/var/db/kav/Quarantine"
#$_deloldfiles $_kav_DEL $_kav_DAY
