#!/usr/bin/perl

use strict;


###################################################################
#
#  Скрипт для удаления старых файлов 
#  Удаляет файлы с датой модификации старше указанной 
#  Удаляет пустые каталоги  
#
#  Использование
#
#  ./deloldfiles /path/to/dir количество_дней
#
#
###################################################################

my $DelPath = shift;
my $DelPeriod = shift;
my $DelCount = 0;

if( $DelPath eq "" or $DelPeriod eq "" or $DelPath eq "/")
{
    print "Use: ./deloldfiles /path/to/dir period\n";
    exit;
}

print "Path to clean  $DelPath \n";

deltree($DelPath);
print "Deleted $DelCount files\n";

sub deltree
{
    my $path = shift;

    my @list = 	`ls -la $path`;
    opendir DIR, $path or return;
    my @list =
        map "$path/$_",
	sort grep !/^\.\.?$/,
	readdir DIR;
	closedir DIR;
    
    foreach(@list)
    {
	chomp;
#	print $_ . " " . -M .  "\n";
	if( -M > $DelPeriod && !-d)
	{
            unlink $_;
	    $DelCount++;
	}
	next unless !-l && -d;
	deltree($_);
        rmdir $_;
    }
}