#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles/qmail
WORK_DIR=/usr/src/qmail
CONF_DIR=/home/SRC/qmail/CONF/qmail-scanner
PATCH_DIR=/home/SRC/qmail/PATCH/qmail-scanner

echo "Install qmail-scanner w/qms-analog"
cd $WORK_DIR
tar xvfz $SRC_DIR/qmail-scanner-1.25.tgz


tar xvfz $SRC_DIR/qms-analog-0.4.4.tar.gz
cd qms-analog-0.4.4
gmake all
cp $PATCH_DIR/qmail-scanner-1.25-st-qms-20050618.patch $WORK_DIR/qmail-scanner-1.25/
cd $WORK_DIR/qmail-scanner-1.25
patch -p1 < qmail-scanner-1.25-st-qms-20050618.patch
sleep 5
cp $PATCH_DIR/qmail-spamorez.patch $WORK_DIR/qmail-scanner-1.25/
patch < qmail-spamorez.patch

sleep 5
host=`hostname`
cat $CONF_DIR/qms-config | sed "s/host.domain.ru/$host/g" >  $WORK_DIR/qmail-scanner-1.25/qms-config
chmod 755 $WORK_DIR/qmail-scanner-1.25/qms-config
echo "Ответить YES на все вопросы!"
sleep 5


cd $WORK_DIR/qmail-scanner-1.25/
./qms-config
echo "Если нет ошибок то далее, если есть см. доку"
sleep 10
./qms-config install
cp $CONF_DIR/quarantine-attachments.txt /data/qmail/qmailscan/
setuidgid vpopmail /var/qmail/bin/qmail-scanner-queue.pl -z
echo '# Spamorez Clean tmp' >> /etc/crontab
echo '0       0      *       *       *       root    setuidgid vpopmail /var/qmail/bin/qmail-scanner-queue.pl -z' >> /etc/crontab
echo '' >> /etc/crontab
killall -s HUP cron
setuidgid vpopmail /var/qmail/bin/qmail-scanner-queue.pl -g
setuidgid vpopmail /var/qmail/bin/qmail-scanner-queue.pl -p
chown -R vpopmail:vchkpw /data/qmail/qmailscan
ln -s /data/qmail/qmailscan /var/log/qmail/qmailscan
mkdir /home/vpopmail/.spamassassin
cp $CONF_DIR/user_prefs /home/vpopmail/.spamassassin/
chown -R vpopmail:vchkpw /home/vpopmail/.spamassassin
echo "Done"

#echo "Install Statistic"
#mkdir /data/STATS
#echo "SPAM Stat"

#cp $CONF_DIR/sa-stats-LIS /data/qmail/bin/tools/
#cp $CONF_DIR/sa-stats.pl /data/qmail/bin/tools/
#echo "# SPAM-Stats" >> /etc/crontab
#echo "1       0       *       *       *       root    /data/qmail/bin/tools/sa-stats-LIS" >> /etc/crontab
#echo "" >> /etc/crontab
#killall -s HUP cron
#sleep 2
#echo "Qmail Stats"
#cp $CONF_DIR/qmailstats /var/qmail/bin/
#chmod 750 /var/qmail/bin/qmailstats
#echo "#Qmail Stats" >> /etc/crontab
#echo "0       3      *       *       *       root    /var/qmail/bin/qmailstats 1>/dev/null 2>/dev/null" >> /etc/crontab
#echo "" >> /etc/crontab
#echo "Install Isoqlog"
#sleep 2
#cd $WORK_DIR
#tar xvfz $SRC_DIR/isoqlog-2.2.1.tar.gz
#cp $PATCH_DIR/isoqlog-2.2.1-LIS.pach $SRC_DIR/isoqlog-2.2.1/
#patch < isoqlog-2.2.1-LIS.pach
#sleep 2
#cd $WORK_DIR/isoqlog-2.2.1
#./configure
#make && make install
#ln -s /data/qmail/control/rcpthosts /usr/local/etc/isoqlog.domains
#host=`hostname`
#cat $CONF_DIR/qmail-1.03/isoqlog.conf |sed "s/host.domain.ru/$host/g" > /usr/local/etc/isoqlog.conf
#cp -R /usr/local/share/isoqlog/htmltemp/library /data/STATS/isoqlog/
#cp -R /usr/local/share/isoqlog/htmltemp/images /data/STATS/isoqlog/
#echo "" >> /etc/crontab
#echo "# Qmail Log Analyser" >> /etc/crontab
#echo "58      *       *       *       *       root    /usr/local/bin/isoqlog 1>/dev/null 2>/dev/null" >> /etc/crontab
#echo "" >> /etc/crontab
#killall -s HUP cron
#echo "Done"

echo "Install Cleaner Carantin"
cp $CONF_DIR/cleaner /data/qmail/bin/
cp $CONF_DIR/deloldfiles /data/qmail/bin/
echo "# Cleaner old files" >> /etc/crontab
echo "0       4       *       *       *       root    /data/qmail/bin/cleaner 1>/dev/null 2>/dev/null" >> /etc/crontab
echo "" >> /etc/crontab
killall -s HUP cron

echo "Спаморез установлен!!!!"
sleep 2
echo "Запускаем Qmail + Спаморез"
#chmod 000 /data/qmail/supervise/qmail-pop3d/log/run
#chmod 000 /data/qmail/supervise/qmail-pop3d/run
#ln -s /var/qmail/supervise/qmail-send /var/qmail/supervise/qmail-smtpd /service
. /etc/rc.local
echo "Done"

cd $pwd
