#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles
WORK_DIR=/usr/src/pbx
CONF_DIR=/home/SRC/pbx/CONF
PATCH_DIR=/home/SRC/pbx/PATCH

mkdir -p $WORK_DIR

echo "Lib PRI"
cd $WORK_DIR

tar zxvf $SRC_DIR/libpri-1.4.10.2.tar.gz
echo "Configure Asterisk"

cd $WORK_DIR/libpri-1.4.10.2

gmake all && gmake install 


echo "Lib SS7"
cd $WORK_DIR

tar zxvf $SRC_DIR/libss7-1.0.2.tar.gz
echo "Configure Asterisk"

cd $WORK_DIR/libss7-1.0.2

gmake all && gmake install 

cd $pwd

