#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles
WORK_DIR=/usr/src
CONF_DIR=/home/SRC/web/CONF
PATCH_DIR=/home/SRC/web/PATCH

#PORTS="textproc/libxml2 graphics/jpeg graphics/png print/freetype print/freetype2"
PORTS="textproc/libxml2 graphics/jpeg graphics/png print/freetype print/freetype2 databases/postgresql91-contrib databases/memcached"

####################################################
for PORT in $PORTS; do

PORT_PATH=/usr/ports/${PORT}

echo install ${PORT_PATH}
cd $PORT_PATH

cp $PATCH_DIR/${PORT}/patch* $PORT_PATH/files

make BATCH=yes FORCE_PKG_REGISTER=1 FORCE_PKG_INSTALL=yes \
install 

make clean

done


cd $pwd