#!/bin/bash

pwd=`pwd`
hostname=`hostname`

SRC_DIR=/home/SRC/distfiles
WORK_DIR=/usr/src
CONF_DIR=/home/SRC/web/CONF
PATCH_DIR=/home/SRC/web/PATCH

PORTS="lang/php53-extensions"

export FORCE_PKG_REGISTER=1

####################################################
for PORT in $PORTS; do

PORT_PATH=/usr/ports/${PORT}

echo install ${PORT_PATH}
cd $PORT_PATH

cp $PATCH_DIR/${PORT}/patch* $PORT_PATH/files

#make BATCH=yes FORCE_PKG_INSTALL=yes \
make FORCE_PKG_INSTALL=yes \
install

done

/usr/local/etc/rc.d/apache22 restart

cd $pwd